# Site settings
title: "Sihyeong Park"
description: "Ph.D Candidate Sihyeong Park"

# Build settings
markdown: kramdown
sass:
  sass_dir: _sass
  style: compressed

# Resume settings
resume_avatar:                  "false"
resume_name:                    "Sihyeong Park"
resume_title:                   "Ph.D Candidate"

# used for the contact button in _layouts/resume.html
resume_contact_email:           "sihyeong@cnu.ac.kr"

# the next two items are used for schema itemprops in _layouts/resume.html
resume_contact_telephone:       ""
resume_contact_address:         "533, EB5, Chungnam National University, Yuseong-gu, Daejeon, Korea"

resume_header_contact_info:     "533, EB5, Chungnam National University, Korea â€¢ sihyeong@cnu.ac.kr"
display_header_contact_info:    "true"

resume_header_intro: "<p>I am majoring in Computer Science and Engineering at Chungnam National University (CNU). I am currently a doctoral student. I'm working on a kernel for multicore embedded real-time systems.</p>"

# use "yes" to display the email contact button,
# "no" to display an "I'm not looking for work" message,
# or remove the resume_looking_for_work option entirely
# to leave blank
resume_looking_for_work:        "no"

# Decide which sections to use
# comment out to hide
resume_section_education:       true
resume_section_publication:      true
resume_section_projects:        true
resume_section_skills:          true
resume_section_recognition:     true
resume_section_links:           false
resume_section_associations:    false
# resume_section_interests:       true

# Resume social links
# uncomment the options you wish to display, and add your own URL
resume_social_links:
  # resume_github_url:            "https://github.com/jglovier/resume-template"
  # resume_twitter_url:           "http://twitter.com/jglovier"
  #resume_dribbble_url:          "https://dribbble.com/jag"
  # resume_facebook_url:          "insert Facebook URL here"
  resume_linkedin_url:          "https://www.linkedin.com/in/sihyeongpark"
  # resume_instagram_url:         "insert your Instagram URL here"
  resume_website_url:           "http://eslab.cnu.ac.kr"
  #resume_medium_url:            "https://medium.com/@jglovier"
resume_print_social_links:      true

# Design settings
resume_theme:                   default

# Note: when editing locally, remember to restart
# your Jekyll server when you edit this file. Changes
# to _config.yml are only recognized when the server starts
